type: bling # configure what to pull in from ublue-os/bling
install:
  - nix-installer # shell shortcuts for determinate system's nix installers
  - container-tools # installs container-related tools onto /usr/bin: kind, kubectx, docker-compose and kubens
  - laptop # installs TLP and configures your system for laptop usage
