# image will be published to ghcr.io/<user>/<name>
name: idros
# description will be included in the image's metadata
description: A starting point for further customization of uBlue images. Make your own! https://ublue.it/making-your-own/

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: files.yml
  - from-file: rpms.yml
  - from-file: flatpaks.yml
  - type: bling # configure what to pull in from ublue-os/bling
    install:
      - nix-installer # shell shortcuts for determinate system's nix installers
      - container-tools # installs container-related tools onto /usr/bin: kind, kubectx, docker-compose and kubens
      - laptop # installs TLP and configures your system for laptop usage
      # - flatpaksync # allows synchronization of user-installed flatpaks, see separate documentation section


  - type: yafti # if included, yafti and it's dependencies (pip & libadwaita)
                #  will be installed and set up
    custom-flatpaks: # this section is optional
      # - Celluloid: io.github.celluloid_player.Celluloid
      # - Krita: org.kde.krita

  - type: script
    scripts:
      # this sets up the proper policy & signing files for signed images to work
      - signing.sh
