title: Welcome to idrOs
properties:
  mode: "run-on-change"
screens:
  first-screen:
    source: yafti.screen.title
    values:
      title: "Welcome to idrOs"
      icon: "/path/to/icon"
      description: |
        This guided installer will help you get started with your new system/
  can-we-modify-your-flatpaks:
    source: yafti.screen.consent
    values:
      title: Welcome!
      condition:
        run: flatpak remotes --columns=name | grep fedora
      description: |
        Replacing Fedora flatpak repo with flathub
      actions:
        - run: flatpak remote-delete --system --force fedora
        - run: flatpak remote-delete --user --force fedora
        - run: flatpak remove --system --noninteractive --all
        - run: flatpak remote-add --if-not-exists --system flathub https://flathub.org/repo/flathub.flatpakrepo
        - run: flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo
  distrobox-containers:
    source: yafti.screen.package
    values:
      title: Choose Distrobox containers
      show-terminal: true
      description: |
        Trialing this for now
      actions:
        - run: mkdir -p ~/Containers/datblygiad
        - run: distrobox create --image ghcr.io/caderidris/datblygiad/datblygiad:latest --name datblygiad --home ~/Containers/datblygiad
  applications:
    source: yafti.screen.package
    values:
      title: Application Installer
      show_terminal: true
      package_manager: yafti.plugin.flatpak
      package_manager_defaults:
        user: false
        system: true
      groups:
        System Apps:
          description: System applications for all desktop environments.
          default: true
          packages:
            - Flatseal (Permission Manager): com.github.tchx84.Flatseal
            - Font Downloader: org.gustavoperedo.FontDownloader
            - Mozilla Firefox: org.mozilla.firefox
            - KeePassXC: org.keepassxc.KeePassXC
            - LocalSend: org.localsend.localsend_app
        Graphics:
          description: Graphical programs
          default: false
          packages:
            - Blender: org.blender.Blender
            - GIMP: org.gimp.GIMP
            - Krita: org.kde.Krita
            - Inkscape: org.inkscape.Inkscape
            - drawio: com.jgraph.drawio.desktop
            - RawTherapee: com.rawtherapee.RawTherapee
            - Boxy SVG: com.boxy_svg.BoxySVG
        Video:
          description: Video programs
          default: false
            - Kdenlive: org.kde.kdenlive
          packages:
            - JellyFin: com.github.iwalton3.jellyfin-media-player
            - mpv: io.mpv.Mpv
        Audio:
          description: Audio programs
          default: false
          packages:
            - Strawberry: org.strawberrymusicplayer.strawberry
            - Reaper: fm.reaper.Reaper
        Gaming:
          description: "Rock and Stone!"
          default: false
          packages:
            - Bottles: com.usebottles.bottles
            - Discord: com.discordapp.Discord
            - Steam: com.valvesoftware.Steam
            - Gamescope (Utility): org.freedesktop.Platform.VulkanLayer.gamescope
            - MangoHUD (Utility): org.freedesktop.Platform.VulkanLayer.MangoHud//22.08
            - SteamTinkerLaunch (Utility): com.valvesoftware.Steam.Utility.steamtinkerlaunch
            - Proton Updater for Steam: net.davidotek.pupgui2
        Office:
          description: Boost your productivity.
          default: false
          packages:
            - LibreOffice: org.libreoffice.LibreOffice
            - Thunderbird Email: org.mozilla.Thunderbird
            - Teams: com.github.IsmaelMartinez.teams_for_linux
        Other:
          description: Other programs
          default: false
          packages:
            - WhatsApp: io.github.mimbrero.WhatsAppDesktop


  final-screen:
    source: yafti.screen.title
    values:
      title: "All done!"
      icon: "/path/to/icon"
      links:
        - "Install More Applications":
            run: /usr/bin/gnome-software
        - "Website":
            run: /usr/bin/xdg-open https://ublue.it
        - "Join the Discord Community":
            run: /usr/bin/xdg-open https://discord.gg/XjG48C7VHx
      description: |
        Thanks for trying uBlue, we hope you enjoy it!
